
version: "3.3"
services:
  nginx:
    build: .
    volumes:
    - ./ngnix:/etc/nginx/templates
    ports:
      - ${IR_NGINX_PORT}:${IR_NGINX_PORT}
    environment:
      - NGINX_HOST=ir.cheminfo.org
      - IR_NGINX_PORT=${IR_NGINX_PORT}
    networks:
      - ir-app
    depends_on:
      - xtbservice
  xtbservice:
    #build: .
    image: ghcr.io/cheminfo-py/xtb-service:0.3.0
    restart: always
    environment:
      - PORT=8091
    expose:
      - "8091"
    networks:
      - ir-app
networks:
  ir-app: