
version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
    - ./ngnix:/etc/nginx/templates
    - ./html:/usr/share/nginx/html
    ports:
      - ${IR_NGINX_PORT}:${IR_NGINX_PORT}
    environment:
      - NGINX_HOST=ir.cheminfo.org
      - IR_NGINX_PORT=${IR_NGINX_PORT}
    networks:
      - ir-app
    depends_on:
      - xtbservice
  xtbservice:
    #build: .
    image: ghcr.io/cheminfo-py/xtb-service:0.3.9
    restart: always
    environment:
      - PORT=8091
      - CACHERDIR=ircache
      - OMP_NUM_THREADS=8,1
      - WORKERS=1
      - MAX_ATOMS=50
      - TIMEOUT=60
    expose:
      - "8091"
    networks:
      - ir-app
    volumes:
      - ./ircache:/ircache
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '4'
networks:
  ir-app:
